#!/usr/bin/env python
# coding: utf-8

import streamlit as st
import pickle
import numpy as np
from PIL import Image

# Load the trained model
model_path = r'C:\Users\HP\Desktop\Data Science\EXCLER Projects\G\gradient_boosting_model1.pkl'
with open(model_path, 'rb') as file:
    model = pickle.load(file)

# Set up the page configuration
st.set_page_config(
    page_title="Solar Power Generation Prediction",
    page_icon="🔆",
    layout="centered"
)

# Display a header image
image = Image.open(r'C:\Users\HP\Desktop\Data Science\EXCLER Projects\G\solarpanel.jpeg')  # Use a relevant image for solar energy
st.image(image, caption="Harnessing the Power of the Sun", use_column_width=True)

# Create a simple form for user input
st.title("Solar Power Generation Prediction")
st.markdown("""
Welcome to the Solar Power Generation Prediction app! This app allows you to input weather and solar data to predict the power generated by solar panels.
""")

# Input fields
st.header("Input Parameters")

distance_to_solar_noon = st.number_input("Distance to Solar Noon")
temperature = st.number_input("Temperature")
wind_direction = st.number_input("Wind Direction")
wind_speed = st.number_input("Wind Speed")
sky_cover = st.number_input("Sky Cover")
visibility = st.number_input("Visibility")
humidity = st.number_input("Humidity")
average_wind_speed_period = st.number_input("Average Wind Speed (Period)")
average_pressure_period = st.number_input("Average Pressure (Period)")

# Create a button for prediction
if st.button("Predict Power Generation"):
    # Prepare the feature vector for prediction
    features = np.array([[distance_to_solar_noon, temperature, wind_direction, wind_speed, sky_cover, visibility, 
                          humidity, average_wind_speed_period, average_pressure_period]])
    
    # Make the prediction
    prediction = model.predict(features)
    
    # Display the prediction
    st.success(f"Predicted Power Generation: {prediction[0]:.2f} joules")

# Footer
st.markdown("""
*This app is powered by a Gradient Boosting model trained on historical solar power generation data.*
""")
